adjust the logic that converts relative to absolute path in bash

diff --git a/install b/install
--- a/install
+++ b/install
@@ -183,72 +183,32 @@ else
     sInstallPrefix=$1
 fi
 
-sMatlabWork="NO_MATLAB"
-sUseMatlab="OFF"
+sMatlabWork=""
 if (( $bMatlabWork == 0 )); then
     if (( $bInstallPrefix == 0 )); then
         echo "Enter path for MATLAB work file (leave empty to disable MATLAB)"
         read -p "matlab work path: " sMatlabWork
-        if [[ -z $sMatlabWork ]]; then
-            sUseMatlab="OFF"
-            sMatlabWork="NO_MATLAB"
-        else
-            sUseMatlab="ON"
-        fi
     fi
 else
-    sUseMatlab="ON"
     sMatlabWork=$2
 fi
 
 echo ""
 
-if [[ $sUseMatlab == "ON" ]]; then
-    if (( $bInstallPrefix == 0 )); then
-        if [ ! -d $sMatlabWork ]; then
-            echo "Matlab work folder $sMatlabWork doesn't exit"
-            read -p "create the folder: (y/N) " sCreate
-            if [[ -z $sCreate ]]; then
-                sCreate="n"
-            fi
-            if [[ $sCreate == "y" ]] || [[ $sCreate == "Y" ]] || [[ $sCreate == "Yes" ]] || [[ $sCreate == "yes" ]]; then
-                mkdir -p $sMatlabWork
-                if [ ! $? == 0 ]; then
-                    echo "ERROR: could not create folder $sMatlabWork"
-                    exit 1;
-                fi
-                # ensure absolute path in $sMatlabWork
-                sPWD=`pwd`
-                cd $sMatlabWork
-                sMatlabWork=`pwd`
-                cd $sPWD
-            else
-                echo "The Matlab interace requires the Matlab work folder,"
-                echo "you must create this or disable Matlab"
-                exit 1;
-            fi
-        else
-            sPWD=`pwd`
-            cd $sMatlabWork
-            if [ ! $? == 0 ]; then
-                echo "ERROR: could not access matlab folder $sMatlabWork"
-                exit 1;
-            fi
-            sMatlabWork=`pwd`
-            cd $sPWD
-        fi
-    else # automatically create $sMatlabWork
-        mkdir -p $sMatlabWork
-        if [ ! $? == 0 ]; then
-            echo "ERROR: could not create folder $sMatlabWork"
-            exit 1;
-        fi
-        # ensure absolute path in $sMatlabWork
-        sPWD=`pwd`
-        cd $sMatlabWork
-        sMatlabWork=`pwd`
-        cd $sPWD
+# cmake seems to handle relative paths as relative to the build folder
+# the user is likely to interpret relative paths to the location of the install script
+# thus we create the folder here and convert the folder to absolute path
+if [[ ! -z $sMatlabWork ]]; then
+    mkdir -p $sMatlabWork
+    if [ ! $? == 0 ]; then
+        echo "ERROR: could not create folder $sMatlabWork"
+        exit 1;
     fi
+    # ensure absolute path in $sMatlabWork
+    sPWD=`pwd`
+    cd $sMatlabWork
+    sMatlabWork=`pwd`
+    cd $sPWD
 fi
 
 
